-- ============================================================
-- Miami-Dade County Budget Explorer - Database Schema
-- Abreu Data Works LLC
--
-- This file is intentionally NOT a schema definition anymore.
--
-- An earlier copy of the schema lived here and drifted out of
-- date with the real database (it predated migrations 002-005:
-- no department_budgets.strategic_area_id, no department_aliases,
-- no glossary_terms, no search_index). Bootstrapping from it
-- produced a database incompatible with both the pipeline and
-- the generated Prisma client.
--
-- Canonical sources:
--   * pipeline/migrations/*.sql  -- ordered, idempotent migrations.
--     Bootstrap or update any database with:
--       python -m pipeline migrate
--   * budget-explorer-web/prisma/schema.prisma -- the Prisma model
--     of the same schema, used to generate the web client.
--
-- Do not add CREATE TABLE statements here; add a new numbered
-- migration instead.
-- ============================================================
